### ISSUE TITLE
Json exception while fetching product details by sku

### ISSUE THREAD

**Issue by alexjones12345** [chen0040/android-magento-client#1]
Caused by: com.alibaba.fastjson.JSONException: exepct '[', but {, type : class com.github.chen0040.magento.models.Product

Please Help me im stuck

**Comment by chen0040** [comment]
Hi @alexjones12345, it is very likely that your magento server api does not return the data in the way that Product class represent at the moment, the reason this can happen may be due to certain fields (e.g. custom attributes or extended attributes) in the Product class does not confirm to your magento server api call, i think the best way to fix this is if you have a test magento account that can be accessed publicly, i can write some demo codes and logging to see what goes wrong in the response JSON deserialiation by fetching data from your magento server. Alternatively, if you have the JSON response data, you can send me the JSON response data for the Product.

**Comment by chen0040** [comment]
@alexjones12345 the issue was caused by magento site not having a standard json representation for extension_attributes and custom_attributes, e.g., the response data for Product can have extension_attributes and custom_attributes in either JSONArray or JSONObject depending on how you configure your magento. I am currently working to address this issue by including a customer deserializer for extension_attributes and custom_attributes. it is working well with the test json response sample for Product, will deploy the new version into nexus for gradle repo

**Comment by chen0040** [comment]
@alexjones12345 The updated version has been deployed to the nexus, you should update your build.gradle to the following line:

compile 'com.github.chen0040:android-magento-client:1.0.5'

To see how it addresses the json response issue, please take a look at and run the ProductJsonUnitTest.java in the src/test of the latest source code of this library, it should pass
