### ISSUE TITLE
Json Exception while getting product details by sku

### ISSUE THREAD

**Issue by ranab4b** [chen0040/android-magento-client#2]
Caused by: com.alibaba.fastjson.JSONException: exepct '[', but {, type : class com.github.chen0040.magento.models.Product

while
// get product detail
Product product = client.products().getProductBySku(sku);

please help me reply back r=to fix i stucked

**Comment by chen0040** [comment]
Hi @ranab4b, it is very likely that your magento server api does not return the data in the way that Product class represent at the moment, the reason this can happen may be due to certain fields (e.g. custom attributes or extended attributes) in the Product class does not confirm to your magento server api call, i think the best way to fix this is if you have a test magento account that can be accessed publicly, i can write some demo codes and logging to see what goes wrong in the response JSON deserialiation by fetching data from your magento server. Alternatively, if you have the JSON response data, you can send me the JSON response data for the Product.

**Comment by ranab4b** [comment]
ok i will share an demo account with u please arrange my demo account so that i can use your existing api
also please tell me where to share the account details

**Comment by chen0040** [comment]
@ranab4b you can send it to my gmail account xs0040@gmail.com

**Comment by ranab4b** [comment]
Sent... please reply back fast i'm stuck with deadline badly

**Comment by chen0040** [comment]
@ranab4b the issue was caused by magento site not having a standard json representation for extension_attributes and custom_attributes, e.g., the response data for Product can have extension_attributes and custom_attributes in either JSONArray or JSONObject depending on how you configure your magento. I am currently working to address this issue by including a customer deserializer for extension_attributes and custom_attributes. it is working well with the test json response sample for Product, will deploy the new version into nexus for gradle repo

**Comment by chen0040** [comment]
@ranab4b The updated version has been deployed to the nexus, you should update your build.gradle to the following line:

compile 'com.github.chen0040:android-magento-client:1.0.5'

To see how it addresses the json response issue, please take a look at and run the ProductJsonUnitTest.java in the src/test of the latest source code of this library, it should pass
